version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/goodspia-source
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 0644

hooks:
#  ApplicationStart:
#    - location: scripts/deploy.sh
#      timeout: 120
#      runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 120