version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/goodspia-source
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 120
      runas: ubuntu