version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/goodspia-source
    overwrite: yes

permissions:
  - object: /home/ubuntu/goodspia-source
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 120
      runas: ubuntu