spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${rds.url}
    username: ${rds.username}
    password: ${rds.password}
  redis:
    host: ${redis.host}
    port: ${redis.port}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
  messages:
    basename: errors
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

logging:
  level:
    org.hibernate.sql: info

server:
  port: 8080

#IAMPORT REST API KEY
iamport:
  rest-api:
    key: ${iamport.rest-api.key}
    secret-key: ${iamport.rest-api.secret-key}
  imp-uid: ${iamport.imp-uid}

#BASE URL
base-url: https://api.goodspia.shop

#JWT SECRET-KEY
jwt:
  secret-key: ${jwt.secret-key}

#S3 AccessKey
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ${aws.region}
    credentials:
      access-key: ${aws.access-key}
      secret-key: ${aws.secret-key}
    s3:
      bucket: ${aws.bucket}