spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
  messages:
    basename: errors

logging:
  level:
    org.hibernate.sql: info

server:
  port: 5000

#IAMPORT REST API KEY
iamport:
  rest-api:
    key: ${iamport.rest-api.key}
    secret-key: ${iamport.rest-api.secret-key}
  imp-uid: ${iamport.imp-uid}

#BASE URL
base-url: https://www.goodspia.shop

#JWT SECRET-KEY
jwt:
  secret-key: ${jwt.secret-key}

springdoc:
  packages-to-scan: shop.goodspia.goods
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
  cache:
    disabled: true
